name: video_testbed
description: "Nostr HLS Demo"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  chewie: ^1.12.1
  flutter:
    sdk: flutter
  flutter_fullscreen: ^1.2.0
  logging: ^1.3.0
  nip01: ^0.3.0+1
  path: ^1.9.1
  statescope: ^3.0.0
  video_player: ^2.10.0
  video_player_web_hls: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
